--=====================================================================================
-- BLU | Localization - English (US) [Base]
-- Author: donniedice
-- Description: English localization strings (base locale; all other locales extend/override)
--=====================================================================================

local addonName = ...
local BLU = _G["BLU"]

-- Initialize localization table
BLU.L = BLU.L or {}
local L = BLU.L

-- Localization function with fallback
function BLU:Loc(key, ...)
    local str = L[key] or key
    if select("#", ...) > 0 then
        return string.format(str, ...)
    end
    return str
end

-- General strings
L["ADDON_LOADED"] = "BLU loaded successfully. Type /blu for options."
L["ADDON_NAME"] = "Better Level-Up!"
L["VERSION"] = "Version"
L["UNKNOWN"] = "Unknown"
L["WELCOME_MESSAGE"] = "Welcome. Use |cff05dffa/blu|r to open the options panel or |cff05dffa/blu help|r for more commands."
L["VERSION_LINE"] = "Version: %s"

-- Command strings
L["CMD_HELP"] = "Shows this help message"
L["CMD_OPTIONS"] = "Opens the options panel"
L["CMD_TEST"] = "Plays a test sound"
L["CMD_RELOAD"] = "Reloads the addon"
L["CMD_DEBUG"] = "Toggles debug mode"
L["CMD_VERSION"] = "Shows addon version"
L["CMD_STILL_LOADING"] = "|cffff9900BLU is still loading...|r"
L["CMD_PLEASE_WAIT"] = "Please wait a moment and try again."
L["CMD_OPTIONS_UNAVAILABLE"] = "|cff00ccffBLU:|r Options panel not available yet. Please wait a moment and try again."
L["CMD_DB_NOT_LOADED"] = "|cff00ccffBLU:|r Database not loaded yet"
L["CMD_DEBUG_ENABLED"] = "|cff00ccffBLU:|r Debug mode %s"
L["CMD_DEBUG_ON"] = "enabled"
L["CMD_DEBUG_OFF"] = "disabled"
L["CMD_ENABLED_MSG"] = "|cff00ff00BLU Enabled|r"
L["CMD_DISABLED_MSG"] = "|cffff0000BLU Disabled|r"
L["CMD_ICON_SHOWN"] = "Minimap icon |cff00ff00shown|r"
L["CMD_ICON_HIDDEN"] = "Minimap icon |cffff0000hidden|r. Use |cffffffff/blu icon on|r to show it again."
L["CMD_ICON_USAGE"] = "Usage: |cffffff00/blu icon on|r or |cffffff00/blu icon off|r"
L["CMD_STATUS_HEADER"] = "|cff00ccffBLU Status:|r"
L["CMD_STATUS_DB"] = "  Database: %s"
L["CMD_STATUS_DB_LOADED"] = "|cff00ff00Loaded|r"
L["CMD_STATUS_DB_NOT_LOADED"] = "|cffff0000Not Loaded|r"
L["CMD_STATUS_PANEL"] = "  Options Panel: %s"
L["CMD_STATUS_PANEL_CREATED"] = "|cff00ff00Created|r"
L["CMD_STATUS_PANEL_NOT_CREATED"] = "|cffff9900Not Created|r"
L["CMD_STATUS_ENABLED"] = "  Enabled: %s"
L["CMD_STATUS_YES"] = "|cff00ff00Yes|r"
L["CMD_STATUS_NO"] = "|cffff0000No|r"
L["CMD_STATUS_DEBUG"] = "  Debug Mode: %s"
L["CMD_STATUS_ON"] = "|cff00ff00On|r"
L["CMD_STATUS_OFF"] = "|cff808080Off|r"
L["CMD_RESCANNING"] = "|cff00ccffBLU:|r Rescanning user custom sounds..."
L["CMD_ADDCUSTOM_USAGE"] = "|cff00ccffBLU:|r Usage: /blu addcustom myfile[.ogg] | Optional Name"
L["CMD_ADDCUSTOM_ADDED"] = "|cff00ccffBLU:|r Added custom sound: %s"
L["CMD_ADDCUSTOM_ADDED_PATH"] = "|cff00ccffBLU:|r Added custom sound: %s (%s)"
L["CMD_ADDCUSTOM_FAILED"] = "|cff00ccffBLU:|r Failed to add custom sound: %s"
L["CMD_REMOVECUSTOM_USAGE"] = "|cff00ccffBLU:|r Usage: /blu removecustom Interface\AddOns\file.ogg"
L["CMD_REMOVECUSTOM_REMOVED"] = "|cff00ccffBLU:|r Removed custom sound: %s"
L["CMD_REMOVECUSTOM_FAILED"] = "|cff00ccffBLU:|r Failed to remove custom sound: %s"
L["CMD_HELP_HEADER"] = "|cff00ccffBLU Commands:|r"
L["CMD_HELP_LINE_OPTIONS"] = "  |cffffff00/blu|r - Open options"
L["CMD_HELP_LINE_DEBUG"] = "  |cffffff00/blu debug|r - Toggle debug mode"
L["CMD_HELP_LINE_STATUS"] = "  |cffffff00/blu status|r - Show addon status"
L["CMD_HELP_LINE_REFRESH"] = "  |cffffff00/blu refresh|r - Rescan external sound packs"
L["CMD_HELP_LINE_ADDCUSTOM"] = "  |cffffff00/blu addcustom <file or path> | <name>|r - Add a custom sound file"
L["CMD_HELP_LINE_REMOVECUSTOM"] = "  |cffffff00/blu removecustom <path>|r - Remove a custom sound file"
L["CMD_HELP_LINE_ENABLE"] = "  |cffffff00/blu enable|r - Enable addon"
L["CMD_HELP_LINE_DISABLE"] = "  |cffffff00/blu disable|r - Disable addon"
L["CMD_HELP_LINE_HELP"] = "  |cffffff00/blu help|r - Show this help"
L["CMD_UNKNOWN"] = "|cff00ccffBLU:|r Unknown command. Type |cffffff00/blu help|r for help."

-- Settings panel strings
L["SETTINGS_TITLE"] = "BLU Settings"
L["GENERAL_TAB"] = "General"
L["SOUNDS_TAB"] = "Sounds"
L["CHANNEL_VOLUME"] = "Channel Volume"
L["MODULES_TAB"] = "Modules"
L["PROFILES_TAB"] = "Profiles"
L["ADVANCED_TAB"] = "Advanced"
L["ABOUT_TAB"] = "About"

-- General panel
L["ENABLE_ADDON"] = "Enable BLU Sound System"
L["MASTER_VOLUME"] = "Master Volume"
L["VOLUME_SETTINGS"] = "Volume Settings"
L["QUICK_SETTINGS"] = "Quick Settings"
L["PLAY_IN_BACKGROUND"] = "Play sounds when game is in background"
L["RANDOM_VARIATIONS"] = "Enable random sound variations"
L["DEBUG_MODE"] = "Enable debug messages"
L["PERFORMANCE"] = "Performance"
L["PRELOAD_SOUNDS"] = "Preload sounds on startup (uses more memory)"
L["SOUND_CACHE_SIZE"] = "Sound cache size:"
L["TEST_BUTTON"] = "Test"
L["GENERAL_DB_NOT_READY"] = "|cffff6666Database not ready. Reopen this tab in a moment.|r"
L["GENERAL_CHANNEL_DESC"] = "All BLU sounds play through the selected channel. Adjusting the volume here changes your in-game channel volume."
L["GENERAL_SOUND_CHANNEL"] = "Sound Channel"
L["GENERAL_CHANNEL_TOOLTIP_TITLE"] = "Sound Channel"
L["GENERAL_CHANNEL_TOOLTIP"] = "Pick which WoW audio channel BLU uses for playback. The volume slider below controls that channel only."
L["GENERAL_VOLUME_TOOLTIP_TITLE"] = "Channel Volume"
L["GENERAL_VOLUME_TOOLTIP"] = "Adjusts the selected WoW sound channel volume. This affects BLU because BLU plays through the selected channel."
L["GENERAL_ENTER_FILE_NAME"] = "|cff00ccffBLU:|r Enter a file name like myfile or myfile.ogg."
L["GENERAL_ADDED_CUSTOM_SOUND"] = "|cff00ccffBLU:|r Added custom sound: %s"
L["GENERAL_ADDED_CUSTOM_SOUND_PATH"] = "|cff00ccffBLU:|r Added custom sound: %s (%s)"
L["GENERAL_ADD_CUSTOM_FAILED"] = "|cff00ccffBLU:|r Failed to add custom sound: %s"
L["GENERAL_CUSTOM_SOUNDS_UNAVAILABLE"] = "|cff00ccffBLU:|r User custom sounds are not available yet."

-- Sounds panel
L["SOUND_CONFIGURATION"] = "Sound Configuration"
L["EVENT_SOUNDS"] = "Event Sounds"
L["SOUND_BROWSER"] = "Sound Browser"
L["SEARCH"] = "Search:"
L["ALL_CATEGORIES"] = "All Categories"
L["DEFAULT_SOUND"] = "Default"
L["ENABLE"] = "Enable"
L["SOUNDS_TAB_HEADER"] = "BLU lists its built-in libraries, your manually added custom sounds, and any supported third-party sound packs. Enable a source to include its sounds in the master list."
L["SOUNDS_MANAGER_HEADER"] = "Add, review, and remove personal sound files for the active profile. BLU can resolve short file names against known folders."
L["SOUNDS_LOADED_COUNT"] = "Loaded: %s"
L["SOUNDS_NO_CUSTOM"] = "No user custom sounds are loaded."
L["SOUNDS_REMOVED_CUSTOM"] = "|cff00ccffBLU:|r Removed custom sound: %s"
L["SOUNDS_REMOVE_CUSTOM_FAILED"] = "|cff00ccffBLU:|r Failed to remove custom sound: %s"
L["SOUNDS_SOURCE_TOOLTIP_INTERNAL"] = "BLU's built-in Warcraft-style defaults."
L["SOUNDS_SOURCE_TOOLTIP_BUILTIN"] = "BLU's built-in game sound library with low, medium, and high variants."
L["SOUNDS_SOURCE_TOOLTIP_USER"] = "Sounds you added manually from the Sounds tab or slash commands."
L["SOUNDS_SOURCE_TOOLTIP_EXTERNAL"] = "Detected from a third-party addon or external media source."
L["SOUNDS_SOURCE_TOOLTIP_REGISTERED"] = "Registered sounds: %s"
L["SOUNDS_LOADED_LABEL"] = "Loaded"

-- Event types
L["EVENT_LEVELUP"] = "Level Up"
L["EVENT_ACHIEVEMENT"] = "Achievement"
L["EVENT_QUEST"] = "Quest Complete"
L["EVENT_REPUTATION"] = "Reputation"
L["EVENT_HONOR"] = "Honor Gain"
L["EVENT_BATTLEPET"] = "Pet Level"
L["EVENT_RENOWN"] = "Renown"
L["EVENT_TRADINGPOST"] = "Trading Post"
L["EVENT_DELVE"] = "Delve Complete"

-- Modules panel
L["MODULE_MANAGEMENT"] = "Module Management"
L["TOTAL_MEMORY"] = "Total Memory Usage: %s"
L["ENABLE_ALL"] = "Enable All"
L["DISABLE_ALL"] = "Disable All"
L["RELOAD_MODULES"] = "Reload Modules"
L["MODULE_ENABLED"] = "Enabled"
L["MODULE_NAME"] = "Module"
L["MODULE_MEMORY"] = "Memory"
L["MODULE_STATUS"] = "Status"
L["MODULE_LOAD_ORDER"] = "Load Order"
L["MODULE_CONFIG"] = "Config"
L["MODULE_ACTIVE"] = "|cff00ff00Active|r"
L["MODULE_DISABLED"] = "|cffff0000Disabled|r"

-- Profiles panel
L["PROFILE_MANAGEMENT"] = "Profile Management"
L["CURRENT_PROFILE"] = "Current Profile"
L["SAVE_PROFILE"] = "Save"
L["NEW_PROFILE"] = "New"
L["DELETE_PROFILE"] = "Delete"
L["RENAME_PROFILE"] = "Rename"
L["PROFILE_PRESETS"] = "Profile Presets"
L["LOAD_PRESET"] = "Load Preset"
L["IMPORT_EXPORT"] = "Import / Export"
L["EXPORT_PROFILE"] = "Export Profile"
L["IMPORT_PROFILE"] = "Import Profile"
L["COPY_FROM_CHARACTER"] = "Copy from Character"
L["SHOW_PROFILE_DIFF"] = "Show profile differences when switching"
L["AUTO_SAVE_PROFILE"] = "Auto-save profile changes"
L["PROFILES_TAB_TITLE"] = "|cff05dffaProfile|r"
L["PROFILES_ACTIVE"] = "Active"
L["PROFILES_DELETE_TOOLTIP"] = "Delete Profile"
L["PROFILES_CHARACTER_LABEL"] = "Character: %s"
L["PROFILES_SAVED_COUNT"] = "Saved: %s"
L["PROFILE_EXISTS"] = "Profile already exists: %s"
L["PROFILE_CREATE_FAILED"] = "Failed to create profile: %s"
L["PROFILE_SELECT_FOR_RENAME"] = "Select a profile and enter a new name."
L["PROFILE_RENAME_DEFAULT"] = "'Default' is a permanent profile and cannot be renamed."
L["PROFILE_NAME_RESERVED"] = "'Default' is a reserved name. Please choose a different name."
L["PROFILE_SELECT_FIRST"] = "Select a profile first."
L["PROFILE_DELETE_DEFAULT"] = "Default cannot be deleted."
L["PROFILE_DELETE_FAILED"] = "Failed to delete profile: %s"
L["PROFILE_PRESET_MISSING_DATA"] = "[Profiles] Preset apply: missing data."
L["PROFILE_PRESET_APPLYING"] = "[Profiles] Applying preset '%s'"
L["PROFILE_PRESET_APPLIED"] = "[Profiles] Preset applied successfully."
L["PROFILE_PRESET_APPLY_FAILED"] = "[Profiles] Preset apply failed: %s"
L["PROFILE_COPY_FAILED"] = "Failed to copy profile: %s"

-- Advanced panel
L["ADVANCED_SETTINGS"] = "Advanced Settings"
L["WARNING_ADVANCED"] = "Warning: These settings are for advanced users"
L["SOUND_ENGINE"] = "Sound Engine"
L["MODULE_SYSTEM"] = "Module System"
L["DEBUGGING"] = "Debugging"
L["EXPERIMENTAL_FEATURES"] = "Experimental Features"
L["INTEGRATION"] = "Integration"
L["MAINTENANCE"] = "Maintenance"
L["CLEAR_CACHE"] = "Clear Sound Cache"
L["RESET_ADVANCED"] = "Reset Advanced Settings"
L["REBUILD_DATABASE"] = "Rebuild Database"

-- About panel
L["FEATURES"] = "Features"
L["CREDITS"] = "Credits"
L["SUPPORT_LINKS"] = "Support & Links"
L["ADDON_STATISTICS"] = "Addon Statistics"
L["MEMORY_USAGE"] = "Memory: %.2f MB"
L["MODULES_COUNT"] = "Modules: %d"
L["SOUNDS_COUNT"] = "Sounds: %d+"
L["LOAD_TIME"] = "Load Time: %s sec"
L["EVENTS_REGISTERED"] = "Events Registered: %d"
L["MAIN_TITLE"] = "|cff05dffaB|r|cffffffffetter |cff05dffaL|r|cffffffffevel-|cff05dffaU|r|cffffffffp|cff05dffa!|r"
L["MAIN_SUBTITLE"] = "Iconic game sounds for World of Warcraft events"
L["MAIN_DISCORD"] = "|cff7289daDiscord:|r |cffffd700discord.gg/N7kdKAHVVF|r"
L["MAIN_AUTHOR"] = "by donniedice"
L["MAIN_BRANDING"] = "|cff8b4b5cRGX|r |cffffd700Mods|r"
L["MAIN_PLACEHOLDER"] = "|cff778899Reserved for a future options panel.|r"

-- Options panel
L["OPTIONS_DB_NOT_READY"] = "Database not ready. Please wait a moment and try again."
L["OPTIONS_QUEUED_AFTER_COMBAT"] = "|cff00ccffBLU:|r Options cannot be opened in combat. Queued to open after combat."
L["OPTIONS_NOT_REGISTERED"] = "Options panel not properly registered."
L["OPTIONS_UNABLE_TO_OPEN"] = "Unable to open options panel"
L["UI_ON"] = "|cff00ff00ON|r"
L["UI_OFF"] = "|cffff0000OFF|r"
L["UI_PLAY"] = "Play"
L["UI_STOP"] = "Stop"
L["UI_SELECT_SOUND"] = "Select Sound"
L["UI_PAGE_COUNT"] = "|cff7fd0ffPage %d/%d|r"
L["UI_PAGE_RANGE"] = "Page %d (%d-%d)"
L["UI_CLOSE"] = "x"
L["COMBAT_TAB_TITLE"] = "|cff05dffaCombat|r"
L["COMBAT_NO_SOUND_SELECTED"] = "|cff00ccffBLU:|r No sound selected for this combat trigger."
L["COMBAT_NO_SOUNDS_AVAILABLE"] = "|cff00ccffBLU:|r No sounds available to preview."
L["COMBAT_INTRO"] = "This tab is a visual test bed for future combat settings. The goal here is to compare direct combat sound options side by side while keeping the layout compact."
L["COMBAT_CUES_NOTE"] = "One-shot sounds that fire at a combat boundary. This is the clearest place for separate start and end cues."
L["COMBAT_MUSIC_NOTE"] = "Persistent combat music should likely live as its own system instead of being mixed into normal one-shot event sounds."
L["COMBAT_MUSIC_STATE"] = "Placeholder behavior: start on combat begin, stop on combat end, with room later for fades, boss-only triggers, and per-boss music."
L["COMBAT_FUTURE_NOTE"] = "This area is for the broader combat-trigger catalog. It keeps the compact 2-column layout so we can add per-trigger rows without redesigning the tab."
L["TABS_PAGE_LABEL"] = "Page %d of %d"
L["UI_HOUSING_TITLE"] = "|cff05dffaHousing Sounds|r"
L["DEBUG_TAB_MASTER"] = "|cff05dffaDebug Mode|r"
L["DEBUG_TAB_TITLE"] = "|cff05dffaDebug Options|r"
L["QUEST_PANEL_TITLE"] = "|cff05dffaB|retter |cff05dffaL|revel-|cff05dffaU|rp! Quest Events"
L["QUEST_CURRENT_SELECTION"] = "Current Selection:"
L["QUEST_NONE"] = "None"
L["QUEST_NONE_DIMMED"] = "|cff888888None|r"
L["QUEST_PLAYING"] = "Playing..."
L["QUEST_TEST"] = "Test"
L["QUEST_DEFAULT_NORMAL"] = "Default (Normal Volume)"
L["QUEST_DEFAULT_VOLUME"] = "Default (%s Volume)"
L["QUEST_CUSTOM"] = "Custom"
L["QUEST_INFO_TEXT"] = "|cff888888The Quest module is automatically enabled when you select a sound for either event.|r"
L["QUEST_NO_SOUND_SELECTED"] = "No sound selected for %s"
L["MINIMAP_ICON_HIDDEN"] = "Minimap icon |cffff0000hidden|r. Use |cffffffff/blu icon on|r to show it again."

-- Messages
L["SETTINGS_SAVED"] = "Settings saved!"
L["MODULE_LOADED"] = "Module loaded: %s"
L["MODULE_CLEANED_UP"] = "Module cleaned up: %s"
L["PROFILE_SAVED"] = "Profile saved: %s"
L["PROFILE_LOADED"] = "Loaded profile: %s"
L["PROFILE_CREATED"] = "Created new profile: %s"
L["PROFILE_DELETED"] = "Deleted profile: %s"
L["PROFILE_RENAMED"] = "Renamed profile: %s to %s"
L["PROFILE_IMPORTED"] = "Profile imported as: %s"
L["CANNOT_DELETE_DEFAULT"] = "Cannot delete Default profile"
L["CANNOT_RENAME_DEFAULT"] = "Cannot rename Default profile"
L["INVALID_PROFILE_DATA"] = "Invalid profile data"
L["ALL_MODULES_ENABLED"] = "All modules enabled"
L["ALL_MODULES_DISABLED"] = "All modules disabled"
L["MODULES_RELOADED"] = "Modules reloaded"
L["CACHE_CLEARED"] = "Sound cache cleared"
L["DATABASE_REBUILT"] = "Database rebuilt"
L["SETTINGS_RESET"] = "Advanced settings reset to defaults"
L["TEST_MODE_ENABLED"] = "Test mode enabled - Click sounds to preview"
L["TEST_MODE_DISABLED"] = "Test mode disabled"
L["OPENING_CONFIG"] = "Opening config for %s"
L["LEVEL_UP"] = "Level up:"
L["ACHIEVEMENT_EARNED"] = "Achievement earned"

-- Errors
L["ERROR_SOUND_NOT_FOUND"] = "Sound not found: %s"
L["ERROR_MODULE_LOAD_FAILED"] = "Failed to load module: %s"
L["ERROR_PROFILE_NOT_FOUND"] = "Profile '%s' not found, switching to Default"
L["ERROR_EVENT_CALLBACK"] = "Error in event %s for %s: %s"
L["ERROR_TIMER_CALLBACK"] = "Error in timer callback: %s"
L["ERROR_HOOK_CALLBACK"] = "Error in hook %s: %s"

-- Module registration
L["ERROR_OPTIONS_PANEL"] = "Cannot register options panel - unsupported WoW version"

-- Debug messages
L["DEBUG_ACHIEVEMENT_PROGRESS"] = "Achievement progress: %s - %s"
L["DEBUG_BATTLE_PET_CAPTURED"] = "Battle pet captured! Index %s"
L["DEBUG_BATTLE_PET_LEVEL_NAME"] = "Battle pet '%s' leveled up to %d!"
L["DEBUG_BATTLE_PET_LEVEL_SLOT"] = "Battle pet leveled up! Slot %d: %d -> %d"
L["DEBUG_COMBAT_ENTERED"] = "Entered combat - UI operations queued"
L["DEBUG_COMBAT_LEFT"] = "Left combat - processing queued operations"
L["DEBUG_COVENANT_RENOWN_INCREASED"] = "Covenant Renown increased: %d -> %d"
L["DEBUG_DELVE_COMPANION_LEVEL"] = "Delve Companion reached level %d!"
L["DEBUG_DELVE_COMPANION_LEVEL_GENERIC"] = "Delve Companion leveled up!"
L["DEBUG_DELVE_LIFE_GAINED"] = "Delve life gained! %d -> %d remaining"
L["DEBUG_DELVE_LIFE_LOST"] = "Delve life lost! %d -> %d remaining"
L["DEBUG_DELVE_SKIPPED_NON_RETAIL"] = "Delve Companion skipped (non-retail client)"
L["DEBUG_EVENT_REGISTERED"] = "Event registered: %s"
L["DEBUG_EVENT_UNREGISTERED"] = "Event unregistered: %s"
L["DEBUG_HONOR_LEVEL_INCREASED"] = "Honor level increased: %d -> %d (%s)"
L["DEBUG_HONOR_LEVEL_RESYNC"] = "Honor level resynced downward: %d -> %d (%s)"
L["DEBUG_HOUSING_DECOR_COLLECTED"] = "Housing decor collected: %s"
L["DEBUG_HOUSING_FAVOR_GAINED"] = "Housing favor increased: %d -> %d"
L["DEBUG_HOUSING_LEVEL_UP"] = "Housing level increased: %d -> %d"
L["DEBUG_HOUSING_REWARDS_RECEIVED"] = "Housing rewards received for level %d"
L["DEBUG_MODULE_LOADED"] = "Module loaded: %s"
L["DEBUG_MODULE_UNLOADED"] = "Module unloaded: %s"
L["DEBUG_OPERATION_QUEUED"] = "Operation queued for after combat"
L["DEBUG_PROFILE_CHANGED"] = "Profile changed to: %s"
L["DEBUG_QUEST_ACCEPTED"] = "Quest accepted: %s"
L["DEBUG_QUEST_COMPLETED"] = "Quest completed: %s"
L["DEBUG_QUEST_PROGRESS"] = "Quest progress: %s"
L["DEBUG_RENOWN_INCREASED"] = "Renown increased with %s: %d -> %d"
L["DEBUG_REPUTATION_INCREASED"] = "Reputation increased with %s: %s -> %s"
L["DEBUG_SOUND_PLAYING"] = "Playing sound: %s (volume: %.2f)"
L["DEBUG_TIMER_EXPIRED"] = "Removed expired combat queue operation"
L["DEBUG_TRADING_POST_CURRENCY_GAINED"] = "Gained %d Trading Post currency!"
L["DEBUG_TRADING_POST_PURCHASE"] = "Trading Post purchase successful!"

-- Register the module
local Localization = {}
function Localization:Init()
    BLU:PrintDebug("Localization module initialized")
end

BLU.Modules = BLU.Modules or {}
BLU.Modules["localization"] = Localization
